### PR TITLE
Matches bonus question design and also removes the uncontrolled state…

### PR DESCRIPTION
**Pull request by polygonart6777**
Matches the design for the bonus question as given in figma.
Design:
Screenshot from 2024-02-11 17-34-03

Implementation:

Screenshot from 2024-02-11 17-35-35

Also fixes the error for uncontrolled radio button group.

### CODE REVIEW

**Comment by polygonart6777** [comment]
Here is a link to the updated design: https://www.figma.com/proto/vWdavWA5nHRkOnTOMFmxQV/Commit2Act?page-id=1771%3A871&type=design&node-id=2833-1172&viewport=-2524%2C706%2C0.34&t=vU5TcWtzENgNrT4E-1&scaling=scale-down&starting-point-node-id=1771%3A874&show-proto-sidebar=1

**Review by klancashire — APPROVED** [review]
Looks great and the clean up pleases my brain! Haha
Don't usually love important tags but sometimes they're unavoidable.

**Comment by stephenbelyea** [comment]
@polygonart6777 I'm finding that when I attempt to use a keyboard for the bonus question (eg. Tab into the radio group and then arrow Up/Down to select an option), it auto-selects an option without me getting a chance to submit or move between options. Not sure if this was meant to be part of the scope, but hopefully something we have a bug logged for!

**Comment by polygonart6777** [comment]
> @polygonart6777 I'm finding that when I attempt to use a keyboard for the bonus question (eg. Tab into the radio group and then arrow Up/Down to select an option), it auto-selects an option without me getting a chance to submit or move between options. Not sure if this was meant to be part of the scope, but hopefully something we have a bug logged for!

Very good point! I've made a ticket here so that we can discuss a possible solution or rethink the design.
https://app.clickup.com/t/86drjx9k1

**Pull request merged**
